name: Build-Test

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - dev
  merge_group:
    branches:
      - dev
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Setup Maven settings
        run: |
          mkdir -p ~/.m2
          cp .github/settings/settings.xml ~/.m2/settings.xml
          
          sed -i "s/\${env.TOKEN}/${{ secrets.USER_TOKEN }}/g" ~/.m2/settings.xml
          sed -i "s/\${env.LOGIN}/${{ secrets.USER_LOGIN }}/g" ~/.m2/settings.xml
        env:
          TOKEN: ${{ secrets.USER_TOKEN }}
          LOGIN: ${{ secrets.USER_LOGIN }}

      - name: Debug Environment Maven
        run: |
          cat ~/.m2/settings.xml

      - name: Clean
        run: |
          ./mvnw clean

      - name: Compile
        run: | 
          ./mvnw validate

      - name: Install
        run: |
          ./mvnw install
